language: go

go:
  - 1.6

script:
  - make test

before_deploy:
  - make build

deploy:
  - provider: s3
    access_key_id: "${AWS_ID}"
    secret_access_key: "${AWS_SECRET}"
    local-dir: bin/latest
    skip_cleanup: true
    upload-dir: "${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}"
    bucket: "buildbot-dashboard"
    region: "eu-west-1"
    acl: public_read
    on:
      all_branches: true
