language: go

go:
  - 1.13.x

script:
  - make test
  - make coverage

before_deploy:
  - make build.docker

deploy:
  - provider: script
    script: ./script/docker_push.sh
    on:
      branch: master
